# Generated by Django 5.2.1 on 2026-05-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0011_question_page_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturevideo",
            name="youtube_url",
            field=models.URLField(help_text="Paste full YouTube URL"),
        ),
    ]
